-- ==============================================================================
-- KAMIDATANG — Skema Database Supabase Multi-Tenancy (Multi-Subdomain)
-- Mendukung kamidatang.com, delta.kamidatang.com, desh.kamidatang.com, dst.
-- Jalankan skrip SQL ini di SQL Editor dashboard Supabase Anda:
-- https://supabase.com/dashboard/project/<project-id>/sql
-- ==============================================================================

-- 1. Buat Tabel Sites (Daftar Subdomain Portal)
CREATE TABLE IF NOT EXISTS public.sites (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    slug TEXT UNIQUE NOT NULL,            -- contoh: 'main', 'delta', 'desh'
    name TEXT NOT NULL,                   -- contoh: 'KAMIDATANG Utama', 'KAMIDATANG Delta'
    tagline TEXT,                         -- contoh: 'Cepat, Jernih & Terpercaya'
    description TEXT,
    logo_badge TEXT DEFAULT 'KD',
    theme_color TEXT DEFAULT '#2563eb',   -- warna aksen
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Buat Tabel Articles dengan Dukungan Multi-Subdomain (site_slug)
CREATE TABLE IF NOT EXISTS public.articles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    site_slug TEXT NOT NULL DEFAULT 'main', -- 'main', 'delta', 'desh', atau 'global' (tayang di semua subdomain)
    title TEXT NOT NULL,
    summary TEXT,
    category TEXT NOT NULL DEFAULT 'Nasional',
    tags JSONB DEFAULT '[]'::jsonb,
    content TEXT NOT NULL,
    author TEXT DEFAULT 'Redaksi KAMIDATANG',
    image TEXT,
    caption TEXT,
    dateline TEXT DEFAULT 'JAKARTA, KAMIDATANG',
    status TEXT NOT NULL DEFAULT 'Terbit',  -- 'Terbit' atau 'Draf'
    is_main_headline BOOLEAN DEFAULT false,
    is_sub_headline BOOLEAN DEFAULT false,
    views INTEGER DEFAULT 0,
    comments JSONB DEFAULT '[]'::jsonb,
    date TEXT,
    time_ago TEXT DEFAULT 'Baru saja',
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Indeks Performa Cepat
CREATE INDEX IF NOT EXISTS idx_articles_site_slug ON public.articles (site_slug);
CREATE INDEX IF NOT EXISTS idx_articles_status ON public.articles (status);
CREATE INDEX IF NOT EXISTS idx_articles_category ON public.articles (category);
CREATE INDEX IF NOT EXISTS idx_articles_views ON public.articles (views DESC);
CREATE INDEX IF NOT EXISTS idx_articles_created_at ON public.articles (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sites_slug ON public.sites (slug);

-- 4. Aktifkan Row Level Security (RLS)
ALTER TABLE public.sites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

-- Drop policy lama jika ada
DROP POLICY IF EXISTS "Public can read sites" ON public.sites;
DROP POLICY IF EXISTS "Public can insert sites" ON public.sites;
DROP POLICY IF EXISTS "Public can update sites" ON public.sites;
DROP POLICY IF EXISTS "Public can delete sites" ON public.sites;

DROP POLICY IF EXISTS "Public can read articles" ON public.articles;
DROP POLICY IF EXISTS "Public can insert articles" ON public.articles;
DROP POLICY IF EXISTS "Public can update articles" ON public.articles;
DROP POLICY IF EXISTS "Public can delete articles" ON public.articles;

-- Kebijakan Akses Sites
CREATE POLICY "Public can read sites" ON public.sites FOR SELECT USING (true);
CREATE POLICY "Public can insert sites" ON public.sites FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can update sites" ON public.sites FOR UPDATE USING (true);
CREATE POLICY "Public can delete sites" ON public.sites FOR DELETE USING (true);

-- Kebijakan Akses Articles
CREATE POLICY "Public can read articles" ON public.articles FOR SELECT USING (true);
CREATE POLICY "Public can insert articles" ON public.articles FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can update articles" ON public.articles FOR UPDATE USING (true);
CREATE POLICY "Public can delete articles" ON public.articles FOR DELETE USING (true);

-- 5. Fungsi Helper Increment View Berita
CREATE OR REPLACE FUNCTION increment_article_views(article_id BIGINT)
RETURNS void AS $$
BEGIN
    UPDATE public.articles
    SET views = COALESCE(views, 0) + 1
    WHERE id = article_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. Aktifkan Realtime Publikasi
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime FOR TABLE public.articles, public.sites;
COMMIT;

-- 7. Seed Data: Daftar Subdomain Awal
INSERT INTO public.sites (slug, name, tagline, description, logo_badge, theme_color)
VALUES
    ('main', 'KAMIDATANG', 'Cepat, Jernih & Terpercaya', 'Portal Berita & Artikel Nasional Utama', 'KD', '#2563eb'),
    ('delta', 'KAMIDATANG Delta', 'Aktual, Berani & Independen', 'Portal Berita & Warta Wilayah Delta', 'KD', '#0284c7'),
    ('desh', 'KAMIDATANG Desh', 'Inspirasi & Gagasan Terdepan', 'Portal Liputan Khusus & Feature Desh', 'KD', '#4f46e5')
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name, tagline = EXCLUDED.tagline;

-- 8. Seed Data: Berita Real Terkini dengan Pembagian Subdomain & 1 Berita Tiap Kanal
INSERT INTO public.articles (
    id, site_slug, title, summary, category, tags, content, author, image, caption, dateline, status, is_main_headline, is_sub_headline, views, comments, date, time_ago
) VALUES
(
    1,
    'main',
    'Presiden Prabowo Lantik Jenderal Dudung Menko Polkam dan Jenderal Suyudi Kapolri dalam Reshuffle Kabinet Merah Putih',
    'Perombakan pos menteri koordinator dan kepemimpinan institusi kepolisian resmi dilakukan di Istana Negara guna memperkuat stabilitas keamanan nasional dan akselerasi program kerja.',
    'Nasional',
    '["Nasional", "Kabinet Merah Putih", "Polri", "Pemerintahan"]'::jsonb,
    '<p><strong>JAKARTA, KAMIDATANG</strong> — Presiden Prabowo Subianto secara resmi melantik perombakan sejumlah posisi menteri dan pimpinan institusi penegak hukum dalam Kabinet Merah Putih di Istana Negara, Jakarta.</p><p>Dalam pelantikan tersebut, Jenderal TNI (Purn) Dudung Abdurachman resmi dipercaya menjabat sebagai Menteri Koordinator Bidang Politik dan Keamanan (Menko Polkam). Sementara itu, tongkat komando Kepolisian Republik Indonesia resmi berganti setelah Jenderal Polisi Suyudi Ario Seto dilantik sebagai Kepala Kepolisian Negara Republik Indonesia (Kapolri) menggantikan Jenderal Listyo Sigit Prabowo.</p><h2>Akselerasi Program Prioritas dan Keamanan Terpadu</h2><p>Dalam amanatnya, Presiden menegaskan bahwa tantangan geopolitik dan perlunya penegakan hukum yang transparan menuntut kepemimpinan yang tanggap dan berintegritas tinggi.</p><blockquote>"Kita membutuhkan aparatur keamanan dan pertahanan yang solid, profesional, dan bekerja tanpa kompromi demi melindungi kedaulatan serta ketertiban segenap tumpah darah Indonesia," tegas Presiden di hadapan para menteri kabinet.</blockquote><p>Langkah reshuffle ini disambut positif oleh kalangan parlemen yang berharap sinergi TNI-Polri dan koordinasi stabilitas politik nasional semakin diperkuat menghadapi kuartal akhir tahun 2026.</p>',
    'Raka Nusantara',
    'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=1000&q=80',
    'Suasana pelantikan menteri dan pimpinan lembaga di Istana Negara Jakarta. (Foto: Dok. Biro Pers Kepresidenan / KAMIDATANG)',
    'JAKARTA, KAMIDATANG',
    'Terbit',
    true,
    false,
    8940,
    '[{"name": "Agus Pratama", "city": "Jakarta", "time": "10 menit lalu", "text": "Semoga jajaran menteri dan Kapolri yang baru mampu menjaga stabilitas hukum dan perlindungan masyarakat secara adil."}]'::jsonb,
    'Jumat, 2 Okt 2026 • 09:15 WIB',
    '25 menit lalu'
),
(
    4,
    'main',
    'Adopsi Ekosistem AI Generatif Lokal Melejit di Indonesia, Akselerasi Efisiensi Bisnis dan Layanan Publik 24 Jam',
    'Integrasi kecerdasan buatan berbasis konteks bahasa Indonesia mencatat lonjakan adopsi hingga 140 persen di sektor perbankan, telekomunikasi, dan ratusan ribu unit usaha UMKM.',
    'Teknologi',
    '["Teknologi", "AI Generatif", "Transformasi Digital", "Cloud"]'::jsonb,
    '<p><strong>JAKARTA, KAMIDATANG</strong> — Pemanfaatan teknologi kecerdasan buatan generatif (Generative AI) yang disesuaikan dengan bahasa dan kebudayaan Indonesia berkembang pesat sepanjang kuartal ketiga dan keempat tahun 2026.</p><p>Berdasarkan data asosiasi teknologi informasi nasional, lebih dari 120.000 badan usaha mulai mengintegrasikan sistem asisten pintar terpadu untuk merespons kebutuhan pelanggan, mengolah data logistik, hingga penyusunan laporan keuangan otomatis.</p><h2>Efisiensi Operasional hingga 60 Persen</h2><p>Penerapan AI lokal ini terbukti memangkas waktu operasional back-office secara signifikan tanpa harus mengorbankan keamanan data perorangan.</p><blockquote>"Solusi kecerdasan buatan masa kini bukan lagi sekadar eksperimen, melainkan tulang punggung daya saing ekonomi digital Indonesia di kancah Asia Tenggara," ungkap pakar analitik digital nasional.</blockquote>',
    'Dimas Prakoso',
    'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80',
    'Pusat pengembangan kecerdasan buatan dan otomatisasi data komputasi awan. (Foto: KAMIDATANG / Dok. Tech)',
    'JAKARTA, KAMIDATANG',
    'Terbit',
    false,
    true,
    5210,
    '[]'::jsonb,
    'Jumat, 2 Okt 2026 • 08:45 WIB',
    '1 jam lalu'
),
(
    5,
    'main',
    'Badan Gizi Nasional Aktivasi 480 Satuan Pelayanan Gizi di 16 Provinsi, Gerakkan Ekonomi Daerah Rp28 Triliun',
    'Pengoperasian 480 Satuan Pelayanan Gizi (SPPG) tahap awal mulai menyerap hasil bumi petani dan peternak lokal, menstimulasi perputaran ekonomi kerakyatan secara masif.',
    'Ekonomi',
    '["Ekonomi", "Badan Gizi Nasional", "Ketahanan Pangan", "UMKM"]'::jsonb,
    '<p><strong>JAKARTA, KAMIDATANG</strong> — Badan Gizi Nasional (BGN) resmi memulai aktivasi operasional 480 unit Satuan Pelayanan Gizi (SPPG) yang tersebar di 16 provinsi per awal Oktober 2026. Seluruh satuan pelayanan ini diproyeksikan beroperasi penuh dalam kurun waktu 3 hingga 4 pekan ke depan.</p><p>Langkah ini tidak hanya berfokus pada pemenuhan nutrisi generasi muda, tetapi juga menjadi instrumen pengungkit ekonomi daerah lewat penyerapan komoditas lokal seperti beras, sayur mayur, telur, dan daging dari koperasi petani terdekat.</p><h2>Multiplier Effect untuk Petani dan Peternak Lokal</h2><p>Kementerian Koordinator Bidang Perekonomian mengestimasi sirkulasi dana tunai langsung di tingkat pedesaan dan sentra pertanian mencapai lebih dari Rp28 triliun pada tahun pertama.</p><blockquote>"Model rantai pasok tertutup yang memprioritaskan petani rakyat memastikan perputaran uang tetap berada di daerah dan memicu pertumbuhan ekonomi berbasis komunitas," jelas juru bicara ketahanan pangan nasional.</blockquote>',
    'Larasati Wijaya',
    'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=800&q=80',
    'Aktivitas transaksi pasokan pangan dan pemantauan rantai pasok ekonomi kerakyatan. (Foto: KAMIDATANG)',
    'JAKARTA, KAMIDATANG',
    'Terbit',
    false,
    true,
    6730,
    '[]'::jsonb,
    'Jumat, 2 Okt 2026 • 08:10 WIB',
    '2 jam lalu'
),
(
    6,
    'main',
    'Bangga Indonesia! Nurisa Dian Ashrifah Raih Medali Emas Panahan Compound Putri Asian Games Aichi-Nagoya',
    'Pemanah andalan Merah Putih Nurisa Dian Ashrifah tampil perkasa menundukkan wakil Filipina di partai final nomor compound individu putri, mendongkrak posisi Indonesia di klasemen medali.',
    'Olahraga',
    '["Olahraga", "Asian Games", "Panahan", "Indonesia Juara"]'::jsonb,
    '<p><strong>NAGOYA, KAMIDATANG</strong> — Lagu kebangsaan Indonesia Raya kembali berkumandang megah di arena panahan Aichi-Nagoya dalam ajang Asian Games 2026. Atlet panahan putri Indonesia, Nurisa Dian Ashrifah, sukses mempersembahkan medali emas di nomor compound perorangan putri.</p><p>Tampil dengan ketenangan luar biasa di bawah tekanan angin kencang, Nurisa sukses mengungguli rival terkuatnya asal Filipina dengan skor tipis 146-144 di babak pamungkas lima seri tembakan.</p><h2>Lonjakan Posisi di Klasemen Sementara</h2><p>Tambahan emas dari cabang panahan ini membawa kontingen Indonesia menempati peringkat ke-13 klasemen perolehan medali dengan total 34 medali, melampaui target awal federasi.</p><blockquote>"Medali emas ini saya persembahkan untuk seluruh rakyat Indonesia yang tiada henti mengirimkan doa dan dukungan. Perjuangan di setiap anak panah adalah untuk kehormatan Merah Putih," ungkap Nurisa sembari berlinang air mata haru.</blockquote>',
    'Fajar Nugroho',
    'https://images.unsplash.com/photo-1511193311914-0346f16efe90?auto=format&fit=crop&w=800&q=80',
    'Konsentrasi atlet panahan Indonesia saat membidik sasaran dalam laga perebutan medali emas. (Foto: Dok. KONI / KAMIDATANG)',
    'NAGOYA, KAMIDATANG',
    'Terbit',
    false,
    false,
    4420,
    '[]'::jsonb,
    'Jumat, 2 Okt 2026 • 07:30 WIB',
    '3 jam lalu'
),
(
    7,
    'main',
    'Peringatan Hari Batik Nasional 2 Oktober: Wastra Nusantara Tembus Panggung Mode Dunia dan Digandrungi Generasi Muda',
    'Perayaan Hari Batik Nasional 2026 disambut meriah dengan kolaborasi desainer muda mengangkat pewarna alam ramah lingkungan dan potongan kasual modern yang mendominasi tren busana harian.',
    'Gaya Hidup',
    '["Gaya Hidup", "Hari Batik Nasional", "Fashion", "Wastra Nusantara"]'::jsonb,
    '<p><strong>SOLO, KAMIDATANG</strong> — Peringatan Hari Batik Nasional pada 2 Oktober 2026 dirayakan serentak di berbagai kota di Tanah Air dengan antusiasme yang kian segar. Batik kini tidak lagi dipandang semata sebagai busana formal kenegaraan, melainkan telah menjelma menjadi identitas gaya hidup dinamis anak muda.</p><p>Gelaran parade wastra di Surakarta, Yogyakarta, dan Jakarta menampilkan ratusan kreasi batik cap dan tulis kontemporer yang dipadukan dengan konsep streetwear kasual dan sneakers.</p><h2>Tren Pewarna Alam dan Keberlanjutan</h2><p>Salah satu sorotan terbesar tahun ini adalah adopsi pewarna alami berbasis daun mangga, kulit kayu tingi, dan indigofera yang ramah lingkungan dan bebas limbah kimia.</p><blockquote>"Generasi muda saat ini sangat menghargai nilai filosofis dan aspek keberlanjutan. Memakai batik adalah wujud kebanggaan budaya sekaligus komitmen pelestarian bumi," tutur kurator busana nusantara terkemuka.</blockquote>',
    'Annisa Maharani',
    'https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?auto=format&fit=crop&w=800&q=80',
    'Kreasi busana batik kontemporer yang menggabungkan motif tradisional dengan siluet streetwear modern. (Foto: Dok. KAMIDATANG Lifestyle)',
    'SOLO, KAMIDATANG',
    'Terbit',
    false,
    false,
    3880,
    '[]'::jsonb,
    'Jumat, 2 Okt 2026 • 07:00 WIB',
    '3 jam lalu'
),
(
    8,
    'main',
    'Kontes Mobil Hemat Energi (KMHE) 2026 Digelar: 64 Kendaraan Inovatif Mahasiswa Unjuk Gigi Capai Rekor 800 Km/Liter',
    'Sebanyak 64 tim perwakilan universitas se-Indonesia bersaing dalam Kontes Mobil Hemat Energi 2026 di Universitas Jember, menghadirkan prototipe aerodinamis bertenaga baterai dan bahan bakar alternatif ramah lingkungan.',
    'Otomotif',
    '["Otomotif", "KMHE 2026", "Mobil Listrik", "Inovasi Energi"]'::jsonb,
    '<p><strong>JEMBER, KAMIDATANG</strong> — Universitas Jember, Jawa Timur, resmi menjadi tuan rumah ajang bergengsi Kontes Mobil Hemat Energi (KMHE) 2026. Sebanyak 64 kendaraan prototipe hemat energi rancangan para insinyur muda dari puluhan perguruan tinggi unjuk kebolehan di lintasan uji coba.</p><p>Kompetisi tahun ini membagi dua kategori utama, yakni Prototipe (kendaraan beroda tiga dengan efisiensi aerodinamika maksimal) dan Urban Concept (kendaraan beroda empat berdesain realistis untuk lalu lintas perkotaan).</p><h2>Rekor Efisiensi dan Rekayasa Material Ringan</h2><p>Para kontestan memanfaatkan material komposit serat karbon berkekuatan tinggi serta motor listrik magnet permanen berdensitas efisiensi hingga 94 persen.</p><blockquote>"Beberapa tim prototipe berhasil mencatatkan rekor konsumsi setara lebih dari 800 kilometer per liter ekuivalen energi listrik. Ini membuktikan talenta teknik muda Indonesia sangat siap memimpin era transportasi ramah lingkungan," jelas ketua dewan juri KMHE 2026.</blockquote>',
    'Bambang Irawan',
    'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
    'Uji efisiensi aerodinamika prototipe kendaraan listrik karya mahasiswa di lintasan sirkuit uji coba. (Foto: Dok. Panitia KMHE / KAMIDATANG Otomotif)',
    'JEMBER, KAMIDATANG',
    'Terbit',
    false,
    false,
    4190,
    '[]'::jsonb,
    'Jumat, 2 Okt 2026 • 06:45 WIB',
    '4 jam lalu'
),
(
    2,
    'delta',
    '[Eksklusif Delta] Modernisasi Kawasan Industri Delta Tarik Investasi Hijau Senilai Rp14 Triliun',
    'Pengembangan koridor industri ramah lingkungan di Delta mulai beroperasi penuh dengan pemanfaatan PLTS atap dan pengelolaan limbah sirkular terpadu.',
    'Ekonomi',
    '["Delta", "Investasi", "Industri Hijau"]'::jsonb,
    '<p><strong>DELTA, KAMIDATANG</strong> — Transformasi kawasan industri terpadu Delta menuju standar net-zero emission membuahkan hasil nyata pada pembukaan kuartal terakhir 2026.</p><p>Sebanyak enam konsorsium manufaktur internasional resmi menandatangani nota kesepahaman komitmen perluasan fasilitas perakitan berteknologi tinggi.</p><h2>Penyediaan Lapangan Kerja Lokal</h2><p>Gubernur daerah setempat menegaskan bahwa prioritas penyerapan tenaga kerja terampil diberikan kepada lulusan politeknik lokal Delta.</p><blockquote>"Kawasan Delta diproyeksikan menjadi episentrum baru manufaktur bersih di Asia Tenggara," ungkap ketua dewan investasi daerah.</blockquote>',
    'Larasati Wijaya',
    'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    'Pusat kendali otomatisasi operasional kawasan industri Delta. (Foto: KAMIDATANG Delta)',
    'DELTA, KAMIDATANG',
    'Terbit',
    true,
    false,
    3120,
    '[]'::jsonb,
    'Jumat, 2 Okt 2026 • 09:00 WIB',
    '1 jam lalu'
),
(
    3,
    'desh',
    '[Sorotan Desh] Komunitas Desain Kreatif Desh Bangun Studio Kolaborasi Terbuka untuk UMKM',
    'Kolektif desainer muda dan pegiat audio-visual Desh meluncurkan program pembinaan identitas merek gratis bagi ratusan pelaku usaha mikro.',
    'Teknologi',
    '["Desh", "Ekonomi Kreatif", "Desain"]'::jsonb,
    '<p><strong>DESH, KAMIDATANG</strong> — Ruang kolaborasi kreatif di kawasan kota lama Desh resmi diperkenalkan pagi ini sebagai wadah akselerasi karya visual dan produk lokal.</p><p>Inisiatif independen ini menyediakan perangkat studio rekaman, percetakan digital mikro, serta lokakarya kurasi kemasan produk bagi pelaku UMKM tanpa dipungut biaya operasional tinggi.</p>',
    'Bagas Pratama',
    'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80',
    'Aktivitas lokakarya desain merek di studio kolaborasi Desh. (Foto: KAMIDATANG Desh)',
    'DESH, KAMIDATANG',
    'Terbit',
    true,
    false,
    2890,
    '[]'::jsonb,
    'Jumat, 2 Okt 2026 • 08:30 WIB',
    '2 jam lalu'
)
ON CONFLICT (id) DO UPDATE 
SET 
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    content = EXCLUDED.content,
    category = EXCLUDED.category,
    tags = EXCLUDED.tags,
    author = EXCLUDED.author,
    image = EXCLUDED.image,
    caption = EXCLUDED.caption,
    is_main_headline = EXCLUDED.is_main_headline,
    is_sub_headline = EXCLUDED.is_sub_headline,
    site_slug = EXCLUDED.site_slug;
